### ISSUE TITLE
Bug when adding new User Equipment [default sd is not 0x111111]

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#120]
Hello
I'm not sure why, but when I deploy your helm charts (using Open5GS and ueransim-ues), the AMF from Open5gs rejects it because it doesn't recognize the sd of the ue. Hence, in order for it to function, I have to manually add the sd to the mongodb database.
I didn't alter any of your chart values.

![Screenshot from 2023-03-06 18-12-33](https://user-images.githubusercontent.com/43995498/223195742-2b3b5ab2-b86c-483c-a016-08c6f3753de2.png)

**Comment by mmarquez999** [comment]
Hello @DiogoCruz40,

In order for the core to accept the connection of the UE that you are launching, it must be previously registered. As you can see in the _values.yaml_ of the open5gs chart, there is a section called _populate_ that allows you to do that when you initialize the core. I'm guessing that you are not changing these values when you deploy the open5gs chart. 

https://github.com/Gradiant/openverso-charts/blob/15c34efa990f677e5aa24c24d42d45e549af7bed/charts/open5gs/values.yaml#L10-L14

We provide a few examples of _initCommands_ that you should use: in this case, you could uncomment the last line in order to add a new subscription for the UE that you will launch, specifying the slice (st: 1 and sd: 0x111111). The subscription will be added to mongodb, so when you deploy the ueransim-ues chart, the default UE will be able to connect to the core automatically.

Hope you find it useful!

**Comment by DiogoCruz40** [comment]
Hey @mmarquez999,

Thank you for your help! I'm closing this issue now.
