### ISSUE TITLE
What is the password for the root of the container Open5gs

### ISSUE THREAD

**Issue by nicolas-gagnon** [Gradiant/openverso-charts#144]
Not able to install some iperft on open5gs-am
i try to add a user but i dont have the password 

 have no name!@open5gs-amf-66f6857b9f-6hv99:~$ su
Password:
>>
I have no name!@open5gs-amf-66f6857b9f-6hv99:~$

**Comment by cgiraldo** [comment]
Hi Nicolas,
This bug is not related with open5gs chart. 
Containers are not VMs. For security reasons the default user of the container is not root and sudo is not installed in the image. I recommend you to use sidecar containers for your case or create your own open5gs image with the tools you need already installed.

For the second option, you can take a look to our open5gs Dockerfile at: 

https://github.com/Gradiant/openverso-images/blob/main/images/open5gs/Dockerfile
