### ISSUE TITLE
open5gs pods multiple replicas (

### ISSUE THREAD

**Issue by jmarkotic** [Gradiant/openverso-charts#90]
hello,
question, not an issue really.
is it safe to scale pods to multiple replicas ? (default is 1 for all components) ?
I can see comment in values.yaml that RWM mode is required if scale is required. Does this apply really to all components pods ?
thanks,
j

**Comment by cgiraldo** [comment]
Hi,

You will not be able to scale de deployments because we defined a HorizontalPodAutoscaler with maxReplicas to 1 in order to avoid people scaling the 5G functions.

If you need for example multiple amfs in your core, you have to deploy multiple open5gs-amfs, each one with a different name (for example playing with the helm release name), in order to register with a unique name in the open5gs-nrf.

If you are thinking in having multiple pods to have some sort of high availability for your 5G function, you can give it a try, but I really don't know the implications on the open5gs core. https://github.com/open5gs/open5gs/issues/1549  does not recommend it.
 
To scale a deployment you need to delete the corresponding hpa resource.

Please, let us know if you test it!

Kind Regards,

**Comment by DiogoCruz40** [comment]
@jmarkotic did you find any alternative?
